import React, { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { ArrowLeft, Plus, Trash2, Send, CheckCircle, User, FileText, Pill } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'

const EMPTY_MED = { medicine_name: '', dosage: '', frequency: '', duration: '', special_instructions: '', quantity: '' }

export default function IssuePrescription() {
  const { user }   = useAuth()
  const location   = useLocation()
  const navigate   = useNavigate()
  const preEmail   = location.state?.patientEmail || ''
  const preApptId  = location.state?.appointmentId || null

  const [form, setForm]       = useState({ patient_email: preEmail, diagnosis: '', additional_notes: '' })
  const [meds, setMeds]       = useState([{ ...EMPTY_MED }])
  const [loading, setLoading] = useState(false)
  const [success, setSuccess] = useState(null)
  const [error,   setError]   = useState('')

  function addMed()         { setMeds(m => [...m, { ...EMPTY_MED }]) }
  function removeMed(i)     { setMeds(m => m.filter((_, idx) => idx !== i)) }
  function updateMed(i, k, v) { setMeds(m => m.map((med, idx) => idx === i ? { ...med, [k]: v } : med)) }

  async function handleSubmit(e) {
    e.preventDefault()
    if (!form.patient_email || !form.diagnosis) { setError('Patient email and diagnosis are required.'); return }
    if (meds.some(m => !m.medicine_name || !m.dosage || !m.frequency || !m.duration)) {
      setError('Please fill in all medication fields (name, dosage, frequency, duration).'); return
    }
    setLoading(true); setError('')

    // 1. Look up patient by email via auth.users (profiles table has no email column)
    const { data: patientId, error: patErr } = await supabase
      .rpc('get_patient_id_by_email', { patient_email: form.patient_email })

    if (patErr || !patientId) {
      setError('No patient account found with that email address.'); setLoading(false); return
    }
    const patData = { id: patientId }

    // 2. Create prescription (token + pin auto-generated by DB)
    const { data: rxData, error: rxErr } = await supabase
      .from('prescriptions')
      .insert({
        doctor_id:       user.id,
        patient_id:      patData.id,
        appointment_id:  preApptId,
        diagnosis:       form.diagnosis,
        additional_notes: form.additional_notes || null,
      })
      .select()
      .single()

    if (rxErr || !rxData) { setError(rxErr?.message || 'Failed to create prescription.'); setLoading(false); return }

    // 3. Insert medications
    const medRows = meds.map((m, i) => ({
      prescription_id:      rxData.id,
      medicine_name:        m.medicine_name,
      dosage:               m.dosage,
      frequency:            m.frequency,
      duration:             m.duration,
      special_instructions: m.special_instructions || null,
      quantity:             m.quantity ? parseInt(m.quantity) : null,
      sort_order:           i,
    }))
    const { error: medErr } = await supabase.from('prescription_medications').insert(medRows)
    if (medErr) { setError(medErr.message); setLoading(false); return }

    setSuccess(rxData)
    setLoading(false)
  }

  if (success) return (
    <div className="max-w-lg mx-auto">
      <div className="card flex flex-col items-center text-center py-14">
        <div className="w-20 h-20 bg-doctor-100 rounded-full flex items-center justify-center mb-5">
          <CheckCircle className="w-10 h-10 text-doctor-600"/>
        </div>
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Prescription Issued!</h2>
        <p className="text-gray-500 text-sm mb-2">The prescription has been securely sent to the patient's portal.</p>
        <div className="bg-gray-50 rounded-xl p-4 w-full text-left mt-2 mb-6 space-y-1.5 text-sm">
          <p><span className="font-semibold text-gray-600">Patient:</span> {form.patient_email}</p>
          <p><span className="font-semibold text-gray-600">Diagnosis:</span> {form.diagnosis}</p>
          <p><span className="font-semibold text-gray-600">Medications:</span> {meds.length}</p>
          <p className="text-xs text-gray-400 mt-2">Pharmacy verification is now linked to the patient's birth year on file.</p>
        </div>
        <div className="flex gap-3 w-full">
          <button onClick={() => { setSuccess(null); setForm({ patient_email:'', diagnosis:'', additional_notes:'' }); setMeds([{...EMPTY_MED}]) }}
            className="btn-primary-doctor flex-1">
            Issue Another Rx
          </button>
          <button onClick={() => navigate('/doctor/prescriptions')} className="btn-outline flex-1">
            View All Rx
          </button>
        </div>
      </div>
    </div>
  )

  return (
    <div className="max-w-2xl mx-auto space-y-5">
      {/* Header */}
      <div className="flex items-center gap-3">
        <button onClick={() => navigate(-1)} className="p-2 hover:bg-gray-100 rounded-xl transition-colors">
          <ArrowLeft className="w-5 h-5 text-gray-600"/>
        </button>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Issue E-Prescription</h1>
          <p className="text-gray-500 text-sm">Create a secure, tamper-proof digital prescription</p>
        </div>
      </div>

      {error && <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl px-4 py-3 text-sm">{error}</div>}

      <form onSubmit={handleSubmit} className="space-y-5">

        {/* Patient */}
        <div className="card">
          <h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2 text-base">
            <User className="w-4 h-4 text-doctor-600"/> Patient
          </h2>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">Patient Email Address</label>
            <input type="email" required placeholder="patient@email.com"
              value={form.patient_email}
              onChange={e => setForm(f => ({ ...f, patient_email: e.target.value }))}
              className="input-doctor"/>
            <p className="text-xs text-gray-400 mt-1.5">Prescription will appear in this patient's E-Prescriptions page</p>
          </div>
        </div>

        {/* Diagnosis */}
        <div className="card">
          <h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2 text-base">
            <FileText className="w-4 h-4 text-doctor-600"/> Diagnosis &amp; Notes
          </h2>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Diagnosis <span className="text-red-400">*</span></label>
              <input required placeholder="e.g., Upper Respiratory Tract Infection"
                value={form.diagnosis}
                onChange={e => setForm(f => ({ ...f, diagnosis: e.target.value }))}
                className="input-doctor"/>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1.5">Doctor's Notes <span className="text-gray-400 font-normal">(optional)</span></label>
              <textarea rows={3} placeholder="Additional instructions or observations..."
                value={form.additional_notes}
                onChange={e => setForm(f => ({ ...f, additional_notes: e.target.value }))}
                className="input-doctor resize-none"/>
            </div>
          </div>
        </div>

        {/* Medications */}
        <div className="card">
          <h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2 text-base">
            <Pill className="w-4 h-4 text-doctor-600"/> Medications
          </h2>

          <div className="space-y-4">
            {meds.map((med, i) => (
              <div key={i} className="bg-gray-50 rounded-2xl p-4 space-y-3 relative">
                <div className="flex items-center justify-between mb-1">
                  <p className="text-sm font-bold text-gray-700">Medication #{i + 1}</p>
                  {meds.length > 1 && (
                    <button type="button" onClick={() => removeMed(i)}
                      className="text-red-400 hover:text-red-600 transition-colors">
                      <Trash2 className="w-4 h-4"/>
                    </button>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-600 mb-1">Medicine Name <span className="text-red-400">*</span></label>
                    <input required placeholder="e.g., Amoxicillin"
                      value={med.medicine_name}
                      onChange={e => updateMed(i, 'medicine_name', e.target.value)}
                      className="input-doctor text-sm py-2"/>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-600 mb-1">Dosage <span className="text-red-400">*</span></label>
                    <input required placeholder="e.g., 500mg"
                      value={med.dosage}
                      onChange={e => updateMed(i, 'dosage', e.target.value)}
                      className="input-doctor text-sm py-2"/>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-600 mb-1">Frequency <span className="text-red-400">*</span></label>
                    <input required placeholder="e.g., 3x a day"
                      value={med.frequency}
                      onChange={e => updateMed(i, 'frequency', e.target.value)}
                      className="input-doctor text-sm py-2"/>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-600 mb-1">Duration <span className="text-red-400">*</span></label>
                    <input required placeholder="e.g., 7 days"
                      value={med.duration}
                      onChange={e => updateMed(i, 'duration', e.target.value)}
                      className="input-doctor text-sm py-2"/>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-600 mb-1">Quantity</label>
                    <input type="number" min="1" placeholder="e.g., 21"
                      value={med.quantity}
                      onChange={e => updateMed(i, 'quantity', e.target.value)}
                      className="input-doctor text-sm py-2"/>
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Special Instructions</label>
                  <input placeholder="e.g., Take after meals"
                    value={med.special_instructions}
                    onChange={e => updateMed(i, 'special_instructions', e.target.value)}
                    className="input-doctor text-sm py-2"/>
                </div>
              </div>
            ))}
          </div>

          {/* Add medication */}
          <button type="button" onClick={addMed}
            className="mt-4 w-full border-2 border-dashed border-doctor-200 hover:border-doctor-400 hover:bg-doctor-50 text-doctor-600 font-semibold py-3 rounded-2xl flex items-center justify-center gap-2 text-sm transition-all">
            <Plus className="w-4 h-4"/> Add Another Medication
          </button>
        </div>

        {/* Submit */}
        <button type="submit" disabled={loading} className="btn-primary-doctor w-full py-4 text-base">
          {loading
            ? <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"/>
            : <><Send className="w-5 h-5"/> Issue Secure Prescription</>}
        </button>
      </form>
    </div>
  )
}
